name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Reusable Workflow
        uses: domjtalbot/ga-repo-test/.github/workflows/test.yml@main